language: php

sudo: false

php:
#  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
  - hhvm

env:
  - DB=mysql PACKAGE_VERSION=high, JACKALOPE_NO_TEST_DB_INIT=1
#  - DB=pgsql PACKAGE_VERSION=high, JACKALOPE_NO_TEST_DB_INIT=1
  - DB=sqlite PACKAGE_VERSION=high, JACKALOPE_NO_TEST_DB_INIT=1


matrix:
  allow_failures:
    - php: hhvm
#  include:
#    - php: 5.3.3
#      env: DB=mysql PACKAGE_VERSION=low
#    - php: 5.3.3
#      env: DB=pgsql PACKAGE_VERSION=low
#    - php: 5.3.3
#      env: DB=sqlite PACKAGE_VERSION=low

before_script:
  - composer selfupdate
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer update --prefer-source --no-interaction
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - php tests/generate_phpunit_config.php $DB

script: php vendor/bin/phpunit -c $DB.phpunit.xml

notifications:
  irc: "irc.freenode.org#jackalope"
